### ISSUE TITLE
Create list of tasks that we can turn into Initial stories

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/knowledgebase#12]
### Overview
We need to surface tasks to make initial stories, in order to create issues.

### Action Items
- [ ] Add comments to this issue with the tasks you think will need to be turned into stories/issues
- [ ] List out the titles of the issues the team agrees to create under resources.
- [ ] Create the issues
- [ ] Copy the template under resources to the new issue and fill out.
-`

#### Issue template
```
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
```

#### Issues team agrees to create
Revisit:
-  [x] #14
-  [x] #15

- Rename
- [x] #21

API
- [ ] #22
- [x] #23
- [ ] #24
- [x] #25

Assets
- [ ] #26
- [ ] #27
- [x] #28
- [x] #29
- [x] #30

Many to Many
- [ ] #35
- [ ] #36
- [ ] #37

Data
- [x] #31
- [ ] #32
- [ ] #33
- [ ] #34

**Comment by ethanstrominger** [comment]
# BOP MVP
- [ ] Authentication
  - [ ] Implement single sign on in Django Admim using AllAuth
  - [ ] Look at different types of tokens and what they are used for and how to create in Django
- [ ] Authorization
  - [ ] Create Admin guide which explains how to add roles and what they do.  Use existing proposal as draft.  Needs to be modified to take approver into account
- [ ] Write up strategy to make PD integration configurable, even after application implemented
- [ ] Rename gdoc to asset group
- [ ] Add BOP topic area (one to many) table and field 
- [ ] Add primary technology as a one to many
- [ ] Add Asset Type (one to many) table and field (google spreadsheet, HTML, PDF, etc)
- [ ] Improve UI for all one to many using this article https://stackoverflow.com/questions/70709775/how-to-hide-specific-field-by-user-group-on-a-django-admin
- [ ] Populate KB tables with preset values on startup
  - [ ] Tools (frameworks)
  - [ ] Status
- [ ] During install, populate tables from PD
  - See spreadsheet for values
- [ ] Decide on strategy for syncing PD and KB data and implement - possibly WebHooks or queues.  
  - [ ] Decide on strategy.  Must take into account that KB app could potentially be down
  - [ ] Implrmrny
- [ ] Create PD user when signing up first time through 
  - [ ] Decide on strategy.  Consider AWS Lambda triggers or queues  
- [ ] Change documentation from user roles to user groups
- [ ] Hide google id (and any future generation screens) for role catalog-maintain and catalog-view
  - See https://stackoverflow.com/questions/70709775/how-to-hide-specific-field-by-user-group-on-a-django-admin
  - [ ] Add catalog-maintain and catalog-view to Admin guide

**Comment by pwalia1** [comment]
Reviewing the Figma Design [here](https://www.figma.com/file/XEr9WwIWKCVLaUZh5VQhXw/BOP-Design?type=design&node-id=2511-50&mode=design&t=lKlnoWyJbuTEKFI4-0) under 'Designs by page name', here are the technical tasks:

- [ ] Create a Data Model to represent the data to show on the website based on the Knowledge base metadata for documents & what is needed to show the customer based on the Figma design.
- [ ] Setup the WebAPI using Django with a project structure that accounts for Controller, Data Model & View. Add connection strings to the PostGres DB in AWS in a config file that can later be provided as a secret in the build pipeline.
- [ ] Provide CRUD endpoints in the Web API using Django. The website probably only needs the Read operation & others are for admin portal.
- [ ] For each page in the Figma design, create an implementation story. For each page, implement the Data Model, Controller & View.
- [ ] Add Unit test project to test the APIs as we develop.
