### ISSUE TITLE
Tasks for Bonnie to reorganize knowledgebase and converter

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/knowledgebase#19]
### Overview
We need to create the repo and drive Infrastructure to separate the knowledgebase and gdoc converter from BOP project.

### Action Items
- [x] Create a new repo Gdoc Converter
   - [x] add repo to existing bop team
- [x] Create new drive knowledgebase.  If doing the double directory, name the second one "knowledgebase ~folder~"
- [x] Do same for gdoc converter
- [ ] Delete these docs - I reviewed all content and for some reason, the docs contain duplicated content
  - https://docs.google.com/document/d/1W4td6G0inCX2q3TAeJqZucIuAitTGcHkmr1WdHyBd78/edit
  -  https://docs.google.com/document/d/1G8wdmTtayEgsVu4F9KdqvGLq_F4Xxecs9dDv17IAER0/edit
  - https://docs.google.com/document/d/1Tx17ewpeI8r7u_-nSazJtUPjKsFeiSYWu-qmJAsbV3I/edit
  - https://docs.google.com/document/d/1nDmDe57lmGcy5KhrEkfTZymIFUL3oNIk9O9XYP7V47o/edit
  - https://docs.google.com/document/d/1qE1TKwuvmu6yWKbx1Z6-wCJOAlgHdjbde8_9enCwXl0/edit
- [ ] Delete this directory https://drive.google.com/drive/folders/1aKoj-eS-nHlpn-DSjyq32BjXqhlJUWgE
- [ ] Delete the shortcut (NOT THE DIRECTORY) titled "Delete this shortcut" and the directory "abc" in https://drive.google.com/drive/folders/1Jf5jmzWDBDdODpYjzJONlMS_6u925Vq-
- [ ] Delete directory https://drive.google.com/drive/folders/1NcR5uE3c3Oh56GQeCOVRcv_k4P94I2a-
- [ ] Optional: Revoke create privileges on top level knowledgebase dir so files do not get accidentally created, only give to the knowledgebase folder.

### Resources/Instructions
- [Gdoc converter repo](https://github.com/hackforla/gdoc-converter)
- [Gdoc converter drive](https://drive.google.com/drive/folders/0ADxmSJXmXMkOUk9PVA)
- [knowledgebase drive](https://drive.google.com/drive/folders/0AJoOnwPk84uwUk9PVA)

**Comment by ExperimentsInHonesty** [comment]
Determine which team members need access to each drive

**Comment by ExperimentsInHonesty** [comment]
@ethanstrominger we don't do this... I'll explain why later 

>  Optional: Revoke create privileges on top level knowledgebase dir so files do not get accidentally created, only give to the knowledgebase folder.
