### ISSUE TITLE
Table: Create Asset Table and move fields from Asset Group

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/knowledgebase#26]
### Overview
As a BOP user, I want to be able to retrieve assets, so that I can read content that is useful to my job.  

# Details
Fields will include: 
- Name
- Description

**The following fields will be moved from Asset Group to Asset**
- Active (T/F) 
- Published (T/F)
- Google ID - Internal
- Slug - Internal

### Action Items
- [ ] Follow instructions on  [Wiki](../wiki) article titled "Technical: Deployment" or similar title to set up environment
- [ ] Follow instructions on  [Wiki](../wiki) article titled "Technical: Create table, api, and tests" for instructions on how to perform these tasks. 
  - [ ] Create model, including running makemigrations.py and migrations.py.
     - [ ] Move columns indicated in detail from AssetGroup to Asset in models.py 
     - [ ] Confirm model for asset group and asset is consistent with [Models wiki article] (https://github.com/hackforla/knowledgebase/wiki/Model-Attributes-and-Relationships) excluding many to many and foreign keys
  - [ ] Register model for admin screen
  - [ ] Verify you can add and list assets
  - [ ] Add serializer
  - [ ] Add view
  - [ ] Add url
  - [ ] Verify api in browser and review swagger documentation
  - [ ] Add tests
  - [ ] Run tests
- [ ] Create pull request 
- [ ] If ready for another bug, look for other bugs as follows:
  -  Look for bugs with labels below or look for issues dependent on this one.
      - ["Category: Table"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22category%3A+table%22)
      - ["Feature: Table: Asset Group"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+table%3A+Asset+Group%22)
      -  ["Feature: Table: Asset"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+table%3A+Asset%22)
   - Look for string "#" in the bug to search for bugs that are dependent on this one being completed

**Comment by CourteousCoder** [comment]
Hi, @ethanstrominger 

Since you're on vacation right now, I'm going to take a stab at this easier ticket while I get acclimated to the codebase.

Thanks!

**Comment by CourteousCoder** [comment]
Below you'll find my progress tracked on it because I don't have write-access to this issue.
> ### Overview
> 
> As a BOP user, I want to be able to retrieve assets, so that I can read content that is useful to my job.
> # Details
> 
> Fields will include:
> 
>     * Name
> 
>     * Description
> 
> 
> **The following fields will be moved from Asset Group to Asset**
> 
>     * Active (T/F)
> 
>     * Published (T/F)
> 
>     * Google ID - Internal
> 
>     * Slug - Internal
> 
> 
> ### Action Items
> 
>     * [x]  Follow instructions on  [Wiki](../wiki) article titled "Technical: Deployment" or similar title to set up environment
> 
>     * [ ]  Follow instructions on  [Wiki](../wiki) article titled "Technical: Create table, api, and tests" for instructions on how to perform these tasks.
>       
>       * [ ]  Create model, including running makemigrations.py and migrations.py.
>         
>         * [ ]  Move columns indicated in detail from AssetGroup to Asset in models.py
>         * [ ]  Confirm model for asset group and asset is consistent with [Models wiki article] (https://github.com/hackforla/knowledgebase/wiki/Model-Attributes-and-Relationships) excluding many to many and foreign keys
>       * [ ]  Register model for admin screen
>       * [ ]  Verify you can add and list assets
>       * [ ]  Add serializer
>       * [ ]  Add view
>       * [ ]  Add url
>       * [ ]  Verify api in browser and review swagger documentation
>       * [ ]  Add tests
>       * [ ]  Run tests
> 
>     * [ ]  Create pull request
> 
>     * [ ]  If ready for another bug, look for other bugs as follows:
>       
>       * Look for bugs with labels below or look for issues dependent on this one.
>         
>         * ["Category: Table"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22category%3A+table%22)
>         * ["Feature: Table: Asset Group"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+table%3A+Asset+Group%22)
>         * ["Feature: Table: Asset"](https://github.com/hackforla/knowledgebase/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+table%3A+Asset%22)
>       * Look for string "#" in the bug to search for bugs that are dependent on this one being completed

**Comment by CourteousCoder** [comment]
Thanks!
