### ISSUE TITLE
M-M: Create Python script to dynamically add Many to Many, using Practice Area

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/knowledgebase#36]
### Blockers/Dependencies
- #35 
- #24 

### Overview
Create Python script to dynamically add Many to Many, using Practice Area so that each asset can be marked as relevant to each practice area.  This will allow the front end interface to display all asset results that are relevant to any specific practice area.

#### Details
- See #24 for advantage of creating autogeneration scripts.  If too complicated, this can be skipped.
- practice areas: engineering, product, ui/ux, etc.

### Action Items
- See #24

### Manual Verification
- Use for generating M-M for #37

### Automated Tests
- No.  Resulting script is manually verified.

**Comment by ExperimentsInHonesty** [comment]
This draft will be complete once Ethan adds action items
