### ISSUE TITLE
Ethan / Bonnie meeting Nov 1 

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/knowledgebase#6]
Agenda
- [ ] FYI
   - I do not have full privileges on issues in BOP. For instance, I cannot add labels or edit comments. This won't matter unless there is some reason to keep BOP.
  - Roster updated (excluding grayed columns)
- [ ]  Team member privileges.  Bonnie:
   - [ ] explain how it works with knowledgebase as an example 
   - [ ] why can't Ethan add teams?
   - [ ] How give developers ability to edit comments and add labels
- [ ] Proposal: Migrate BOP project to regular project. 
  - In knowledgebase repo you can't create a classic project, so seems GitHub wants projects to be migrated. 
  - Project boards work the same
  - Non-classic projects have some cool features
     - Can have multiple repos
     - Additional useful views 
- [ ] Proposal: Transfer issues from BOP to Knoweledgebase through UI one a time. It could also be done in bulk programatically from the terminal, but UI is probably faster.
- [ ] Review [TODOs](https://github.com/hackforla/knowledgebase/blob/main/TODO.md) for creating bugs

**Comment by ExperimentsInHonesty** [comment]
This issue has been replaced with this https://github.com/hackforla/knowledgebase/issues/11#issuecomment-1787578536
